version: '3'

services:

  resume:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 18080:80
    volumes:
      - ./test:/opt/test
      - test-volume12:/var/log


volumes:
   test-volume12