version: '3'

services:

  resume:
    build:
      context: .
      dockerfile: ./Dockerfile
      no_cache: true
    ports:
      - 18080:80
    volumes:
      - ./test:/opt/test
      - test-volume12:/var/log

  resume12:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 18081:80
    volumes:
      - /data/compose/27/test:/opt/test/
      - ./web:/web



volumes:
   test-volume12: {}