name: Test create env

on:
#  push:
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs: 
  create_env_file_job:
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      #- name: Create .env file
      #  uses: ozaytsev86/create-env-file@v1
      #  with:
      #    ENV_TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
      #    ENV_ANOTHER_KEY: ${{ secrets.ANOTHER_KEY }}
      - name: Run your script
        run: |
          GITHUB_COMMIT=${{ github.ref }}
          echo $GITHUB_COMMIT
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          echo $GITHUB_SHA_SHORT
          echo $GITHUB_ENV

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        env: 
          GIT_HUB_PUB_KEYS: ${{ vars.GIT_HUB_PUB_KEYS }}
          MAIN_LOCAL_PHP: ${{ secrets.MAIN_LOCAL_PHP }}
          PARAM_LOCAL_PHP: ${{ secrets.PARAM_LOCAL_PHP }}
        with:
          host: ${{ secrets.PROD_IP }}
          username: root
          key: ${{ secrets.PROD_SERVER_KEY }}
          envs: GITHUB_SHA_SHORT,GIT_HUB_PUB_KEYS,PARAM_LOCAL_PHP,MAIN_LOCAL_PHP
          script: |
            export GITHUB_SHA_SHORT=$GITHUB_SHA_SHORT
            export GIT_HUB_PUB_KEYS=$GIT_HUB_PUB_KEYS
            echo $GIT_HUB_PUB_KEYS > ~/github_pub_kes
            echo "Github commit: $GITHUB_SHA_SHORT"
            echo $GITHUB_SHA_SHORT
            DIR=${WEB_DIR}/${GITHUB_SHA_SHORT}-`date -Isec`
            echo $DIR
            echo "${PARAM_LOCAL_PHP}" | base64 --decode > ~/params-local.php
            cat ~/params-local.php
            echo "${MAIN_LOCAL_PHP}" | base64 --decode > ~/main-local.php
            cat ~/main-local.php
